<!DOCTYPE html>
<html>
<body>
<?php
$n = "do your task";
echo $n;
echo "<br>";
   echo strlen("what is your name?");
   echo "<br>";
   echo str_word_count("my name is farah");
   echo "<br>";
   echo strrev("my name is farah");
   echo "<br>";
   echo strpos("welcome to my task page","task");
   echo "<br>";
   echo str_replace("farah","sara","this is farah page");
   echo "<br>";
   
   define("name","farah");
   $name = "sara";
   echo name;
  
       ?>
    </body>
</html>
